# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Install_AND_Test_Node
  displayName: Install & Test Node 
  jobs:
  - job: Test_Client
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: Test Client
    - script: npm i
  - job: ChosePipelines
    displayName: 'ChosePipelines'
    steps:
    - bash: |
        CHANGED_FILES=$(git diff HEAD HEAD~ --name-only)
        for FILE in $CHANGED_FILES
          do
            if [[ $FILE == src/* ]]; then
              echo "MATCH:  ${FILE} changed"
              echo "##vso[task.setvariable variable=src;isOutput=true]src"
            fi
          done
      name: setvarStep

- stage: Deploy
  displayName: "Deploy"
  dependsOn: Install_AND_Test_Node
  condition: succeeded()
  jobs:
  - job: Deploy_Hosting
    variables:
      textVar: $[ stageDependencies.Install_AND_Test_Node.ChosePipelines.outputs['setvarStep.src'] ]
    condition: eq(variables.textVar, 'src') #map doThing and check the value
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: "Deploy Hosting: crwn-clyne" 
    - script: |
        npm install
        npm run build
        npm install -g firebase-tools
        firebase target:apply hosting crwn-clyne crwn-clyne
        firebase deploy --token $(FIREBASE_TOKEN) --project $(FB_PROJECT) --only hosting:crwn-clyne


        
